version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sns-to-sqs"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-2647npur4ct5"
s3_prefix = "sns-to-sqs"
region = "us-east-1"
profile = "developertwo"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
